# Generated by Django 2.2.4 on 2019-10-26 22:07

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyDfkx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='部门编号')),
                ('department', models.CharField(max_length=255, unique=True, verbose_name='部门名称')),
                ('index', models.CharField(max_length=255)),
                ('hidden', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '地方科协组织',
                'verbose_name_plural': '地方科协组织',
                'db_table': 'agency_dfkx',
            },
        ),
        migrations.CreateModel(
            name='AgencyJg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='部门编号')),
                ('department', models.CharField(max_length=255, unique=True, verbose_name='部门名称')),
                ('index', models.CharField(max_length=255)),
                ('hidden', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '科协机关及事业单位',
                'verbose_name_plural': '科协机关及事业单位',
                'db_table': 'agency_jg',
            },
        ),
        migrations.CreateModel(
            name='AgencyQgxh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='部门编号')),
                ('department', models.CharField(max_length=255, unique=True, verbose_name='部门名称')),
                ('index', models.CharField(max_length=255)),
                ('hidden', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '全国学会组织',
                'verbose_name_plural': '全国学会组织',
                'db_table': 'agency_qgxh',
            },
        ),
        migrations.CreateModel(
            name='ChannelToDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=255, unique=True)),
                ('database', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': '频道和数据库的映射',
                'verbose_name_plural': '频道和数据库的映射',
                'db_table': 'channelToDatabase',
            },
        ),
        migrations.CreateModel(
            name='ChinaTopNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻链接')),
                ('img', models.ImageField(blank=True, max_length=255, null=True, upload_to='mgh', verbose_name='新闻图片')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='新闻内容')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='发布时间')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻来源')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻标签')),
                ('comment', models.IntegerField(blank=True, default=0, verbose_name='评论数')),
                ('like', models.IntegerField(blank=True, default=0, verbose_name='点赞')),
                ('priority', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='优先级')),
                ('hidden', models.BooleanField(blank=True, default=True, verbose_name='是否推送')),
                ('today', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': '中央领导人新闻',
                'verbose_name_plural': '中央领导人新闻',
                'db_table': 'chinaTopNews',
            },
        ),
        migrations.CreateModel(
            name='DFKX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻链接')),
                ('img', models.ImageField(blank=True, max_length=255, null=True, upload_to='mgh', verbose_name='新闻图片')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='新闻内容')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='发布时间')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻来源')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻标签')),
                ('comment', models.IntegerField(blank=True, default=0, verbose_name='评论数')),
                ('like', models.IntegerField(blank=True, default=0, verbose_name='点赞')),
                ('priority', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='优先级')),
                ('hidden', models.BooleanField(blank=True, default=True, verbose_name='是否推送')),
                ('today', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': '地方科协新闻',
                'verbose_name_plural': '地方科协新闻',
                'db_table': 'dfkx',
            },
        ),
        migrations.CreateModel(
            name='KX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻链接')),
                ('img', models.ImageField(blank=True, max_length=255, null=True, upload_to='mgh', verbose_name='新闻图片')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='新闻内容')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='发布时间')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻来源')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻标签')),
                ('comment', models.IntegerField(blank=True, default=0, verbose_name='评论数')),
                ('like', models.IntegerField(blank=True, default=0, verbose_name='点赞')),
                ('priority', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='优先级')),
                ('hidden', models.BooleanField(blank=True, default=True, verbose_name='是否推送')),
                ('today', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': '中国科协新闻',
                'verbose_name_plural': '中国科协新闻',
                'db_table': 'kx',
            },
        ),
        migrations.CreateModel(
            name='KxLeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名字')),
                ('hidden', models.BooleanField(blank=True, default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '科协领导',
                'verbose_name_plural': '科协领导',
                'db_table': 'leaders',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻链接')),
                ('img', models.ImageField(blank=True, max_length=255, null=True, upload_to='mgh', verbose_name='新闻图片')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='新闻内容')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='发布时间')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻来源')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻标签')),
                ('comment', models.IntegerField(blank=True, default=0, verbose_name='评论数')),
                ('like', models.IntegerField(blank=True, default=0, verbose_name='点赞')),
                ('priority', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='优先级')),
                ('hidden', models.BooleanField(blank=True, default=True, verbose_name='是否推送')),
                ('today', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': '时政要闻',
                'verbose_name_plural': '时政要闻',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='QGXH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻链接')),
                ('img', models.ImageField(blank=True, max_length=255, null=True, upload_to='mgh', verbose_name='新闻图片')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='新闻内容')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='发布时间')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻来源')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻标签')),
                ('comment', models.IntegerField(blank=True, default=0, verbose_name='评论数')),
                ('like', models.IntegerField(blank=True, default=0, verbose_name='点赞')),
                ('priority', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='优先级')),
                ('hidden', models.BooleanField(blank=True, default=True, verbose_name='是否推送')),
                ('today', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': '全国学会新闻',
                'verbose_name_plural': '全国学会新闻',
                'db_table': 'qgxh',
            },
        ),
        migrations.CreateModel(
            name='TECH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻链接')),
                ('img', models.ImageField(blank=True, max_length=255, null=True, upload_to='mgh', verbose_name='新闻图片')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='新闻内容')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='作者')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='关键字')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='发布时间')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻来源')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='新闻标签')),
                ('comment', models.IntegerField(blank=True, default=0, verbose_name='评论数')),
                ('like', models.IntegerField(blank=True, default=0, verbose_name='点赞')),
                ('priority', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='优先级')),
                ('hidden', models.BooleanField(blank=True, default=True, verbose_name='是否推送')),
                ('today', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': '科技热点新闻',
                'verbose_name_plural': '科技热点新闻',
                'db_table': 'tech',
            },
        ),
    ]
